config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:edit, :update]
  
  root "rooms#index"
  resources :rooms, only: [:index, :new, :create, :show] do
    resources :comas, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coma.rb
class Coma < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image

  validates :image, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :comas
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms
  has_many :comas
  
  validates :name, presence: true, uniqueness: { case_sensitive: true }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comas_controller.rb
class ComasController < ApplicationController
  def create
   coma = Coma.create(coma_params)
   redirect_to "/rooms/#{coma.room.id}"
  end

  private
  def coma_params
    params.require(:coma).permit(:image).merge(user_id: current_user.id, room_id: params[:room_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_room, only: [:show]

  def index
    query = "SELECT * FROM rooms"
    @rooms = Room.find_by_sql(query)
  end

  def new
    @room = Room.new
  end

  def create
    Room.create(room_params)
    redirect_to root_path
  end

  def show
    @coma = Coma.new
    @comas = @room.comas.includes(:user)
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end
  def room_params
    params.require(:room).permit(:name).merge(user_id: current_user.id)
  end

  def coma_params
    params.permit(:image).merge(room_id: @room.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comas_helper.rb
module ComasHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FourComa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<%= render "shared/header" %>

<%= link_to '4コマroomを作る', new_room_path %>
<div>
<% @rooms.each do |room| %>
  <ul>
  <li><%= room.name %></li>
  <%= link_to '詳細', room_path(room.id), method: :get %>
  <ul>
<% end %>
</div>

app/views/rooms/new.html.erb
<%= form_with(model: @room, local: true) do |form| %>
      <%= form.text_field :name, placeholder: "お題" %>
      <%= form.submit "SEND" %>
<% end %>

app/views/rooms/show.html.erb
<%= render "shared/header" %>

<div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@room, @coma], local: true) do |form| %>
        <%= form.file_field :image, placeholder: "画像乗っける", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>

<div class="comments">
  <h4>＜四コマ一覧＞</h4>
  <% @comas.each do |coma| %>
    <p>
      <strong><%= link_to coma.user.name, "/users/#{coma.user_id}" %>：</strong>
      <%= image_tag coma.image.variant(resize: '500x500'), class: 'coma-image' if coma.image.attached? %>
    </p>
  <% end %>
</div>

app/views/shared/_header.html.erb
<% if user_signed_in? %>
  <%= current_user.name %>
  <%= link_to image_tag("kuri_logo.jpg", class:"kuri-icon"), "/" %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to '新規登録', new_user_registration_path %>
  <%= link_to 'ログイン', new_user_session_path %>
<% end %>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>